### ISSUE TITLE
Charms to be integrated with prometheus 

### ISSUE THREAD

**Issue by orfeas-k** [canonical/bundle-kubeflow#837]
This is a tracker issue to document progress with CKF charms that can be integrated with Grafana (aka provide a functional and useful grafana dashboard) 

- [ ] [admission-webhook](https://github.com/canonical/admission-webhook-operator)
- [x] [argo-controller](https://github.com/canonical/argo-operators/tree/main/charms/argo-controller/src) All of these alerts seem to follow upstream [docs](https://argo-workflows.readthedocs.io/en/latest/metrics/#default-controller-metrics) about workflows. I couldn't verify that they 're working apart from the `unit_available.rule` (did `pebble stop argo-controller`) since I didn't know how to trigger a workflow that would deterministically fail or log errors.
- [ ] [dex](https://github.com/canonical/dex-auth-operator) There's a `unit_available.rule` that is working (did `pebble stop dex`).
- [ ] [envoy](https://github.com/canonical/envoy-operator) There's a `unit_available.rule` that is working (deleted its `deployment`).
- [ ] [istio-gateway](https://github.com/canonical/istio-operators/blob/main/charms/istio-gateway/src/charm.py). Need to expose the endpoint in the service and create a MetricsEndpoint.
- [ ] [istio-pilot](https://github.com/canonical/istio-operators/tree/main/charms/istio-pilot/src) There is an `istio.rule` but it is not working (read [here](https://github.com/canonical/bundle-kubeflow/issues/822#issuecomment-1956486352)). Metrics however are exposed.
- [x] [jupyter-controller](https://github.com/canonical/notebook-operators/tree/main/charms/jupyter-controller) 	There are the some alerts but I have some second thoughts about them (read [here](https://github.com/canonical/bundle-kubeflow/issues/822#issuecomment-1956486352))
- [ ] [jupyter-ui](https://github.com/canonical/notebook-operators/tree/main/charms/jupyter-ui)
- [ ] [katib-controller](https://github.com/canonical/katib-operators/tree/main/charms/katib-controller) There's a `unit_available.rule` that is working (deleted its `deployment`).
- [ ] [katib-db-manager](https://github.com/canonical/katib-operators/tree/main/charms/katib-db-manager)
- [ ] [katib-ui](https://github.com/canonical/katib-operators/tree/main/charms/katib-ui)
- [ ] [kfp-api](https://github.com/canonical/kfp-operators/tree/main/charms/kfp-api) There's a `unit_available.rule` that is working (did `pebble stop apiserver`).
- [ ] [kfp-metadata-writer](https://github.com/canonical/kfp-operators/tree/main/charms/kfp-metadata-writer)
- [ ] [kfp-persistence](https://github.com/canonical/kfp-operators/tree/main/charms/kfp-persistence)
- [ ] [kfp-profile-controller](https://github.com/canonical/kfp-operators/tree/main/charms/kfp-profile-controller)
- [ ] [kfp-schedwf](https://github.com/canonical/kfp-operators/tree/main/charms/kfp-schedwf)
- [ ] [kfp-ui](https://github.com/canonical/kfp-operators/tree/main/charms/kfp-ui)
- [ ] [kfp-viewer](https://github.com/canonical/kfp-operators/tree/main/charms/kfp-viewer)
- [ ] [kfp-viz](https://github.com/canonical/kfp-operators/tree/main/charms/kfp-viz)
- [ ] [knative-eventing](https://github.com/canonical/knative-operators/tree/main/charms/knative-eventing) Metrics from knative-eventing and serving charms are exposed given that needed `otel-collector` relations exist ([spec](https://docs.google.com/document/d/12VO6EQwzjhg2kZQDCltiPW7aZJR-cSCaMXj62tJ8TfU/edit))
- [ ] [knative-serving](https://github.com/canonical/knative-operators/tree/main/charms/knative-serving) Metrics from knative-eventing and serving charms are exposed given that needed `otel-collector` relations exist ([spec](https://docs.google.com/document/d/12VO6EQwzjhg2kZQDCltiPW7aZJR-cSCaMXj62tJ8TfU/edit))
- [ ] [knative-operator](https://github.com/canonical/knative-operators/tree/main/charms/knative-operator)
- [ ] [kserve-controller](https://github.com/canonical/kserve-operators/blob/main/charms/kserve-controller/src/charm.py)
- [ ] [kubeflow-dashboard](https://github.com/canonical/kubeflow-dashboard-operator)
- [ ] [kubeflow-rofiles(kfam)](https://github.com/canonical/kubeflow-profiles-operator/blob/main/src/charm.py)
- [ ] [kubeflow-roles](https://github.com/canonical/kubeflow-roles-operator/)
- [ ] [kubeflow-volumes](https://github.com/canonical/kubeflow-volumes-operator/blob/main/src/charm.py)
- [ ] [metacontroller](https://github.com/canonical/metacontroller-operator/blob/main/src/charm.py) There's a `unit_available.rule` that is working (deleted its `sts`).
- [ ] [minio](https://github.com/canonical/minio-operator/) There's a `unit_available.rule` that is working (deleted its `sts`).
- [ ] [mlmd](https://github.com/canonical/mlmd-operator)
- [ ] [oidc-gatekeeper](https://github.com/canonical/oidc-gatekeeper-operator/blob/main/src/charm.py)
- [ ] [pvcviewer-operator](https://github.com/canonical/pvcviewer-operator/)
- [x] [seldon-controller-manager](https://github.com/canonical/seldon-core-operator) There are alerts. They are working but not everything is tested  (read [here](https://github.com/canonical/bundle-kubeflow/issues/822#issuecomment-1956486352))
- [ ] [tensorboard-controller](https://github.com/canonical/kubeflow-tensorboards-operator/tree/main/charms/tensorboard-controller)
- [ ] [tensorboard-web-app](https://github.com/canonical/kubeflow-tensorboards-operator/blob/main/charms/tensorboards-web-app/src/charm.py)
- [ ] [training-operator](https://github.com/canonical/training-operator/blob/main/src/charm.py) There's a `unit_available.rule` that is working (did `pebble stop training-operator`).

**Comment by orfeas-k** [comment]
#### Istio-pilot
It looks like istio-pilot endpoint is misconfigured since [the `/metrics` path is not provided at all](https://github.com/canonical/istio-operators/blob/e0d2c0261a3760366b87e7be27100393009967ac/charms/istio-pilot/src/charm.py#L195). Curling the same service but adding a `/metrics` at the end replies with actual metrics.

**Comment by rgildein** [comment]
@orfeas-k Should we update this issue?

**Comment by rgildein** [comment]
I'm closing this issue because it's not updated and metrics have already been added everywhere, where upstream support it. More information can be found in epic KF-5558.
